[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --production=false", "cd admin && npm install --production=false"]

[phases.build]
cmds = ["cd admin && npm run build"]

[start]
cmd = "node src/index.js"
